name: Schedule PR Merge

on:
  workflow_dispatch:
    inputs:
      pr_number:
        description: 'PR Number'
        required: true
        type: number
      merge_time_ist:
        description: 'Merge Time in IST (YYYY-MM-DDTHH:MM)'
        required: true
        type: string

jobs:
  schedule-merge:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Convert IST to UTC and calculate cron expression
      id: calculate-cron
      run: |
        merge_time_ist="${{ github.event.inputs.merge_time_ist }}:00" # Append seconds as 00
        merge_time_utc=$(date -d "$merge_time_ist +0530" -u +"%Y-%m-%dT%H:%M:%SZ")
        cron_minute=$(date -d "$merge_time_utc" +'%M')
        cron_hour=$(date -d "$merge_time_utc" +'%H')
        cron_day=$(date -d "$merge_time_utc" +'%d')
        cron_month=$(date -d "$merge_time_utc" +'%m')
        cron_expression="$cron_minute $cron_hour $cron_day $cron_month *"
        echo "cron_expression=$cron_expression" >> $GITHUB_ENV
    - name: Create scheduled workflow
      run: |
        pr_number="${{ github.event.inputs.pr_number }}"
        cron_expression="${{ env.cron_expression }}"
        cat << "EOF" > .github/workflows/merge-pr-${pr_number}.yml
        name: Merge PR #${pr_number}
        
        on:
          schedule:
            - cron: '${cron_expression}'
        jobs:
          merge:
            runs-on: ubuntu-latest
            steps:
            - name: Checkout repository
              uses: actions/checkout@v3
            - name: Merge PR
              uses: actions/github-script@v4
              with:
                script: |
                  await github.pulls.merge({
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    pull_number: ${pr_number}
                  });
        EOF
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git add .github/workflows/merge-pr-${pr_number}.yml
        git commit -m "Schedule merge for PR #${pr_number}"
        git push
